# Generated by Django 4.2.5 on 2023-10-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=259)),
                ('course_name', models.CharField(max_length=259)),
            ],
            options={
                'db_table': 'Course',
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(blank=True, max_length=259)),
                ('dept_name', models.CharField(max_length=259)),
            ],
            options={
                'db_table': 'Department',
                'ordering': ['dept_id'],
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_id', models.CharField(blank=True, max_length=259)),
                ('purpose_name', models.CharField(max_length=259)),
            ],
            options={
                'db_table': 'Purpose',
                'ordering': ['purpose_id'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=259)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('material', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.course')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.purpose')),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department'),
        ),
    ]
